apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metal-lb
spec:
  destination:
    name: ''
    namespace: metal-lb
    server: 'https://kubernetes.default.svc'
  source:
    path: Applications/Argocd/Metal-lb/metal-lb.yaml
    repoURL: 'https://metallb.github.io/metallb'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated: null
    syncOptions:
      - CreateNamespace=true
