apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metal-lb
spec:
  destination:
    name: ''
    namespace: metal-lb
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://metallb.github.io/metallb'
    targetRevision: 0.14.5
    chart: metallb
  sources: []
  project: default
  syncPolicy:
    automated: null
    syncOptions:
      - CreateNamespace=true
      - Validate=false
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - PruneLast=true
      - RespectIgnoreDifferences=true
